Document GroupEnum natives
lep/jassdoc pull request #135
Opened 2024-04-22 00:03 UTC by WaterKnight

Needs review

2024-04-22 01:03 UTC, Luashine requested changes
Incredibly detailed testing!

I just had a thought, do you insist on _PR review comment -> change_ style workflow throughout? I haven't tried but Github allows maintainers to submit changes to PRs, if it is easy to use then we could switch to wiki-style changes at least for tiny grammar fixes like "in bulk" so I don't have to write a separate comment under each of them and instead quickly fix it myself.

Of course question-answer type of requests must go the old way.

2024-04-22 01:16 UTC, WaterKnight commented on common.j
> +@param countLimit Maximum amount of units to be considered.
Difficult to know when it does not work at all :D maybe test on an old patch.

2024-04-22 01:23 UTC, WaterKnight commented on common.j
> +@note Does not consider locust units. Locust units cannot be spatially enumerated.
Player- and type-based enums do pick locusts. Range and Rect do not. I inverted the note to say that Range and Rect do not pick locusts. Could of course add notes to both, I just felt like it's rather a limitation of spatial picking with locusts than a special feature of player- and type-based picking.

2024-04-22 01:34 UTC, WaterKnight commented
Add note about hidden units

2024-04-22 01:37 UTC, WaterKnight commented
Add note about dependency equivalent in type-based picking

2024-04-22 07:01 UTC, WaterKnight commented on common.j
> +Clears a group and then adds units of a unit type name to it.
Wanted to be clear about that a name is used rather than the usual integer representation. Or is it okay if this is just indicated by the parameter type? Maybe we should at least indicate that this name interface is used in some different natives like also in `CreateUnitByName` by using a common notation.

2024-04-22 23:27 UTC, Luashine commented on common.j
> +Clears a group and then adds units of a unit type name to it.
OK I understand you. The function's name to be considered too "native GroupEnumUnitsOfType". However now when I read just this line in isolation, I honestly still cannot understand from "unit type name" what exactly this represents. Then I would still need to read the argument description, which is great and very clear. If I think of various unit types there are, the unit classification comes to mind first (Undead, Mechanical, Tauren, Ward and so on).

---

- Current: "native GroupEnumUnitsOfType: Clears a group and then adds units of a unit type name to it."
- Matching wording: "native GroupEnumUnitsOfType: Clears a group and then adds units of matching unit type name to it."
- Shortened: "native GroupEnumUnitsOfType: Clears a group and then adds units of matching type to it."

The modern naming scheme would have called it "ByTypeName".

The canonical [CreateUnit](https://lep.duckdns.org/jassbot/doc/CreateUnit) calls the number unitid --> UnitNameId? [CreateUnitByName](https://lep.duckdns.org/jassbot/doc/CreateUnitByName) really calls it "unitname". Then comes [unittype](https://lep.duckdns.org/jassbot/search?query=unittype) which is its own variable type to describe the unit classification flags.

The description I had used for this 2 years ago was "internal name" and I didn't know it allowed `custom_<FourCC>` naming scheme - see [UnitId2String](https://lep.duckdns.org/jassbot/doc/UnitId2String)

---

With this listed I can't make up my mind :sweat_smile: It's either ambiguous or too long and clunky to word.

Still please add the "matching" **or** change the "a" -> "the" article there, because in the context of using this function, the user will have _a **specific** type name_ in mind, making it _the type name_  LOL :face_with_spiral_eyes:

2024-04-22 23:28 UTC, Luashine commented on common.j
> +@note Does not consider locust units. Locust units cannot be spatially enumerated.
> Range and Rect do not. I inverted the note to say that Range and Rect do not pick locusts. Could of course add notes to both, I just felt like it's rather a limitation of spatial picking with locusts

I have heard so many times that these triggers don't work with locust that I had assumed this applied to all of them. I'd wage adding explicit notes to all of them then

> This does (not) enum units with Locust.

2024-04-22 23:31 UTC, Luashine commented on common.j
> +@param countLimit Maximum amount of units to be considered.
haha I asked here because I didn't see or notice? a `@bug` note here but it's in `@note` rn. Closing this one off. :heavy_check_mark:

2024-04-24 08:02 UTC, lep commented
Big thanks from me aswell. From my side it all works (markdown looks correct and the few checks i have don't complain). So once you both are happy with this feel free to merge/rebase/whatever.

2024-04-25 13:24 UTC, Luashine approved these changes

2024-04-25 13:26 UTC, merged