Document data synchronization via SyncStoredX natives
lep/jassdoc pull request #84
Opened 2022-11-08 20:09 UTC by lep

Trying to document the data synchronisation process using SyncStoredX natives.
I think I've got the process right but I would like to hear your opinion @WaterKnight @Luashine @cipherxof @Frotty 
Also I don't know how those new `BlzSendSyncData` stuff fits into this.

2022-11-08 20:25 UTC, lep commented
Other questions: what does `TriggerSyncStart` do? What about `SyncSelections`?

2022-11-09 10:35 UTC, Luashine commented
The reason I opened #63 (as you can guess) is that I don't know but wanted to save the links I found and hoped that someone else knew. I didn't read them yet :) Of all of us I've probably spent the least time reading guides and whatnot.

If we wanted to ask about these for real (outside of user-side knowledge) then we should consider pinging Unryze and MindWorX. 

iirc `TriggerSyncStart` is used in FileIO and is actually a "sync finished" event, `SyncSelections` is currently selected units for all players.

2022-11-09 15:30 UTC, Luashine requested changes

2022-11-09 15:30 UTC, Luashine commented on gamecache.j
> +context (citation needed), that is everybody if called simply as is.
> Calling this function sends a sync packet from each player in the calling
> context (citation needed), _that is everybody if called simply as is._

Worded ambiguously. 

> context (citation needed). That is, a simple call sends a packet from everyone to everyone.
> If you want only one player be the source of the sync, execute it locally with `GetLocalPlayer`.

2022-11-09 15:30 UTC, Luashine commented on gamecache.j
> +lways) that is the packet coming from the game host.
a missing in `lways`

2022-11-09 15:30 UTC, Luashine commented on gamecache.j
> +More interesting perhaps is the use to synchronize local data (like a players
player**'s** apostrophe

2022-11-09 15:30 UTC, Luashine commented on gamecache.j
> +syncing process.
Add: `i.e. first sync will be received first (FIFO).` for clarity

2022-11-09 15:30 UTC, Luashine commented on trigger.j
> +Waits until all currently running `SynctedStoredX` (like `SyncStoredInteger`)
SynctedStoredX -> SyncStoredX

2022-11-09 17:31 UTC, WaterKnight commented on gamecache.j
> +syncing process.
Is this guaranteed even if the network packets are in disorder? Are the sync actions numbered?

2022-11-11 14:57 UTC, lep commented on gamecache.j
> +syncing process.
I don't know but I think everyone is assuming it is.

2022-11-12 11:16 UTC, merged